import { HugeiconsIcon } from "@hugeicons/react";
import {
  ArrowDown02Icon,
  ArrowUp02Icon,
  Cancel01Icon,
  CubeIcon,
  GridViewIcon,
  MoreHorizontalIcon,
  Search01Icon,
  Tick02Icon,
  HeartIcon,
  Book01Icon,
  ArrowLeftRightIcon,
  Settings02Icon,
  Rotate360Icon,
  ZoomInIcon,
  ZoomOutIcon,
  RefreshIcon,
  Share01Icon,
  PlayIcon,
  PauseIcon,
  SparklesIcon,
  ArrowLeft02Icon,
  ArrowRight02Icon,
  HelpCircleIcon,
  FlaskConicalIcon,
  Award01Icon,
} from "@hugeicons/core-free-icons";

const icons = {
  search: Search01Icon,
  menu: MoreHorizontalIcon,
  up: ArrowUp02Icon,
  down: ArrowDown02Icon,
  spread: CubeIcon,
  table: GridViewIcon,
  done: Tick02Icon,
  close: Cancel01Icon,
  favorite: HeartIcon,
  learn: Book01Icon,
  compare: ArrowLeftRightIcon,
  settings: Settings02Icon,
  rotate: Rotate360Icon,
  zoomIn: ZoomInIcon,
  zoomOut: ZoomOutIcon,
  reset: RefreshIcon,
  share: Share01Icon,
  play: PlayIcon,
  pause: PauseIcon,
  spark: SparklesIcon,
  previous: ArrowLeft02Icon,
  next: ArrowRight02Icon,
  help: HelpCircleIcon,
  sandbox: FlaskConicalIcon,
  award: Award01Icon,
};

// Keep the prototype's icon box, stroke weight and accessible button labels.
export function Icon({ name }: { name: keyof typeof icons }) {
  return <HugeiconsIcon icon={icons[name]} size={20} strokeWidth={2.2} aria-hidden="true" />;
}
