/** Worker source is emitted by the statically generated /sw.js route. */
export const serviceWorkerSource = [
  "/* Elementals: public, same-origin offline content only. Cache version is generated for each production build. */",
  "const VERSION = __CACHE_VERSION__;",
  "const SHELL = `${VERSION}-shell`;",
  "const PAGES = `${VERSION}-pages`;",
  "const ASSETS = `${VERSION}-assets`;",
  "const offlineClients = new Set();",
  'const CORE = ["/", "/elements", "/playground", "/offline.html", "/element-data.json", "/manifest.webmanifest", "/icons/icon-192.png", "/icons/icon-512.png", "/icons/maskable-512.png"];',
  'const FONTS = ["/fonts/nunito-variable.woff2", "/fonts/jetbrains-mono-500.ttf", "/fonts/jetbrains-mono-700.ttf"];',
  "",
  'self.addEventListener("install", (event) => {',
  "  event.waitUntil((async () => {",
  "    const shell = await caches.open(SHELL);",
  "    await shell.addAll(CORE);",
  "    const assets = await caches.open(ASSETS);",
  '    const documents = await Promise.all(["/", "/playground"].map(async (path) => (await shell.match(path)).text()));',
  '    const html = documents.join("\\n");',
  "    // Save the production shell's JS and CSS before declaring it available offline.",
  "    const urls = [...html.matchAll(/(?:src|href)=[\"']([^\"']+)[\"']/g)]",
  '      .map((match) => new URL(match[1].replace(/&amp;/g, "&"), self.location.origin))',
  '      .filter((url) => url.origin === self.location.origin && url.pathname.startsWith("/_next/static/"))',
  "      .map((url) => url.href);",
  "    await assets.addAll([...new Set(urls)]);",
  "    await Promise.allSettled(FONTS.map((font) => assets.add(font)));",
  "  })());",
  "});",
  'self.addEventListener("activate", (event) => {',
  "  event.waitUntil((async () => {",
  '    await Promise.all((await caches.keys()).filter((key) => key.startsWith("elementals-") && ![SHELL, PAGES, ASSETS].includes(key)).map((key) => caches.delete(key)));',
  "    await self.clients.claim();",
  "  })());",
  "});",
  'self.addEventListener("message", (event) => {',
  '  if (event.data?.type === "SKIP_WAITING") self.skipWaiting();',
  '  if (event.data?.type === "GET_OFFLINE_STATUS") event.source?.postMessage({ type: "OFFLINE_STATUS", offline: offlineClients.has(event.source.id) });',
  '  if (event.data?.type === "CLEAR_OFFLINE_STATUS") offlineClients.delete(event.source?.id);',
  "});",
  "// These caches contain only public HTML or same-URL static assets. Next.js's",
  "// RSC Vary fields and transport Accept-Encoding must not hide a saved document",
  "// from a later navigation. RSC, API, and range requests never enter this path.",
  "const PUBLIC_MATCH = { ignoreVary: true };",
  "async function savePage(request, response) {",
  '  if (!response.ok || !response.headers.get("content-type")?.includes("text/html")) return;',
  "  // Clone while the fetch response is still unused, before yielding to cache I/O.",
  "  const copy = response.clone();",
  "  const cache = await caches.open(PAGES);",
  "  await cache.put(request, copy);",
  "  const keys = await cache.keys();",
  "  if (keys.length > 150) await cache.delete(keys[0]);",
  "}",
  'self.addEventListener("fetch", (event) => {',
  "  const request = event.request;",
  "  const url = new URL(request.url);",
  '  if (request.method !== "GET" || url.origin !== self.location.origin || url.pathname.startsWith("/api/") || request.headers.has("range") || request.headers.has("rsc") || url.searchParams.has("_rsc")) return;',
  '  if (request.mode === "navigate") {',
  "    event.respondWith((async () => {",
  "      try {",
  "        const response = await fetch(request);",
  "        offlineClients.delete(event.resultingClientId || event.clientId);",
  "        event.waitUntil(savePage(request, response).catch(() => {}));",
  "        return response;",
  "      } catch {",
  "        offlineClients.add(event.resultingClientId || event.clientId);",
  "        const pages = await caches.open(PAGES);",
  "        const shell = await caches.open(SHELL);",
  '        return await pages.match(request, PUBLIC_MATCH) || await pages.match(url.pathname, PUBLIC_MATCH) || await shell.match(url.pathname, PUBLIC_MATCH) || await shell.match("/offline.html", PUBLIC_MATCH);',
  "      }",
  "    })());",
  "    return;",
  "  }",
  '  if (url.pathname.startsWith("/_next/static/") || url.pathname.startsWith("/fonts/") || url.pathname.startsWith("/icons/") || url.pathname === "/element-data.json") {',
  "    event.respondWith((async () => {",
  "      const cached = await caches.match(request, PUBLIC_MATCH);",
  "      if (cached) return cached;",
  "      const response = await fetch(request);",
  '      if (response.ok && response.type === "basic") {',
  "        const cache = await caches.open(ASSETS);",
  "        await cache.put(request, response.clone());",
  "      }",
  "      return response;",
  "    })());",
  "  }",
  "});",
].join("\n");
